//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nancy.OpenApi.Tests.Fakes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FakeModuleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FakeModuleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nancy.OpenApi.Tests.Fakes.FakeModuleResources", typeof(FakeModuleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;description&quot;: &quot;Multiple status values can be provided with comma separated strings&quot;,
        ///    &quot;operationId&quot;: &quot;findPetsByStatus&quot;,
        ///    &quot;parameters&quot;: [
        ///        {
        ///            &quot;collectionFormat&quot;: &quot;multi&quot;,
        ///            &quot;description&quot;: &quot;Status values that need to be considered for filter&quot;,
        ///            &quot;in&quot;: &quot;query&quot;,
        ///            &quot;items&quot;: {
        ///                &quot;default&quot;: &quot;available&quot;,
        ///                &quot;enum&quot;: [
        ///                    &quot;available&quot;,
        ///                    &quot;pending&quot;,
        ///                    &quot;sold&quot;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetApiTest {
            get {
                return ResourceManager.GetString("GetApiTest", resourceCulture);
            }
        }
    }
}
