//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nancy.OpenApi.WebHost {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nancy.OpenApi.WebHost.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.
        /// </summary>
        internal static string BasePath {
            get {
                return ResourceManager.GetString("BasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to joe.bloggs@somewhere.com.
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joe Bloggs.
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://joe-bloggs.com.
        /// </summary>
        internal static string ContactUrl {
            get {
                return ResourceManager.GetString("ContactUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Api demonstrating different http verbs and the rendering of api descriptions.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External community wiki article.
        /// </summary>
        internal static string ExternalDocsDescription {
            get {
                return ResourceManager.GetString("ExternalDocsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.wikiarticle.com.
        /// </summary>
        internal static string ExternalDocsUrl {
            get {
                return ResourceManager.GetString("ExternalDocsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT.
        /// </summary>
        internal static string LicenseName {
            get {
                return ResourceManager.GetString("LicenseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://joe-bloggs.com.
        /// </summary>
        internal static string LicenseUrl {
            get {
                return ResourceManager.GetString("LicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test terms of service to go here..
        /// </summary>
        internal static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World Api.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
